### ISSUE TITLE
Duplicate key error when you turn on loop and use v-for to render the slides

### ISSUE THREAD

**Issue by leo-rojas** [BKWLD/vue-ssr-carousel#76] opened 2022-07-26 20:53 UTC
I'm getting a duplicate key warning message when looping through the slides and setting the loop property to true.  Is there a proper way to do this without getting the error?  Here's an example bit of code:
```
<ssr-carousel :loop="true">
   <div class="slide" v-for="(item, index) in items" :key="index">
         {{ item.content }}
   </div>
</ssr-carousel>
```

If I set the :loop property to false, the error goes away.

Thanks

**Comment by weotch** [comment] 2022-08-30 20:18
I think this is a duplicate of #81

**Closed** 2022-08-31 16:20 UTC
Labels: resolved
